name: Deploy Quarto e Upload para Google Drive

on:
  push:
    branches: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Fazer checkout do código do repositório
        uses: actions/checkout@v4

      - name: Instalar o R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'
          use-public-rspm: true

      - name: Verificar e instalar htmlwidgets
        run: |
          R -e "if (!require(htmlwidgets)) install.packages('htmlwidgets'); library(htmlwidgets); cat('htmlwidgets OK\n')"

      - name: Instalar dependências do R
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 1
          packages: |
            any::knitr
            any::rmarkdown
            any::downlit
            any::xml2
            any::ggplot2
            any::dplyr
            any::htmlwidgets

      - name: Configurar o ambiente do Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Atualizar o Quarto
        run: quarto update

      - name: Renderizar o projeto Quarto
        run: quarto render --to html

      - name: Publicar no Quarto Pub
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          QUARTO_PUB_AUTH_TOKEN: ${{ secrets.QUARTO_PUB_AUTH_TOKEN }}

      - name: Compactar todo o repositório
        run: zip -r repository-archive.zip .

      - name: Upload para Google Drive
        uses: Jumbo810/Upload_Github_Artifacts_TO_GDrive@v2.2.2
        with:
          target: 'repository-archive.zip'
          parent_folder_id: ${{ secrets.GDRIVE_FOLDER_ID }}
          credentials: ${{ secrets.GDRIVE_CREDENTIALS }}
          name: 'commit-${{ github.sha }}.zip'